default:
  image: "docker.io/abb128/android-build:latest@sha256:8df16e2badb5e42d2f5e3862683c7ff0ebdcc348affe059385e42eebef79302f"

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_FORCE_HTTPS: "true"

stages:          # List of stages for jobs, and their order of execution
  - test
  - buildDev
  - buildRelease

unit-test-job:
  stage: test
  tags:
    - docker
  script:
    - gradle testDevDebugUnitTest -s
  artifacts:
    reports:
      junit:
        - ./app/build/test-results/testDevDebugUnitTest/*.xml 

buildDev:
  stage: buildDev
  tags:
    - docker
  script:
    - ./setUpPropertiesCI.sh
    - gradle assembleDevRelease -s
    - mv app/build/outputs/apk/dev/release/app-dev-release.apk ./app-release-$CI_COMMIT_SHORT_SHA.apk
    - ./sendZulipMessage.sh "New Voice Input dev build - https://gitlab.futo.org/alex/voiceinput/-/jobs/$CI_JOB_ID/artifacts/raw/app-release-$CI_COMMIT_SHORT_SHA.apk"
  artifacts:
    name: "app-release-$CI_COMMIT_SHORT_SHA"
    paths: 
      - ./*.apk
  when: manual

buildRelease:
  stage: buildRelease
  tags:
    - docker
  script:
    - ./setUpPropertiesCI.sh
    - gradle bundlePlayStoreRelease -s
    - gradle assembleStandaloneRelease -s
    - gradle assembleFDroidRelease -s
    - mv app/build/outputs/bundle/playStoreRelease/app-playStore-release.aab ./playStore.aab
    - mv app/build/outputs/apk/standalone/release/app-standalone-release.apk ./standalone.apk
    - mv app/build/outputs/apk/fDroid/release/app-fDroid-release.apk ./fdroid.apk
  artifacts:
    name: "release-$CI_COMMIT_SHORT_SHA"
    paths: 
      - ./*.aab
      - ./*.apk
  only:
    - tags
  except:
    - branches
  when: manual