default:
  image: "docker.io/abb128/android-build:latest@sha256:8df16e2badb5e42d2f5e3862683c7ff0ebdcc348affe059385e42eebef79302f"

stages:          # List of stages for jobs, and their order of execution
  - test
  - buildDevRelease
  - buildPlayStoreRelease

unit-test-job:
  stage: test
  script:
    - gradle testDevDebugUnitTest -s
  artifacts:
    reports:
      junit:
        - ./app/build/test-results/testDevDebugUnitTest/*.xml 

buildDevRelease:
  stage: buildDevRelease
  script:
    - ./setUpKeysCI.sh
    - gradle assembleDevRelease -s
    - mv app/build/outputs/apk/dev/release/app-dev-release.apk ./app-release-$CI_COMMIT_SHORT_SHA.apk
    - ./sendZulipMessage.sh "New dev build - https://gitlab.futo.org/alex/voiceinput/-/jobs/$CI_JOB_ID/artifacts/raw/app-release-$CI_COMMIT_SHORT_SHA.apk"
  artifacts:
    name: "app-release-$CI_COMMIT_SHORT_SHA"
    paths: 
      - ./*.apk
  when: manual

buildPlayStoreRelease:
  stage: buildPlayStoreRelease
  script:
    - ./setUpKeysCI.sh
    - gradle bundlePlayStoreRelease -s
    - mv app/build/outputs/bundle/playStoreRelease/app-playStore-release.aab .
  artifacts:
    name: "playStore-release-$CI_COMMIT_SHORT_SHA"
    paths: 
      - ./*.aab
  only:
    - tags
  except:
    - branches
  when: manual
