image:
  name: "docker.io/abb128/android-build:latest"

stages:          # List of stages for jobs, and their order of execution
  - test
  - build

build-job:
  stage: build
  script:
    - ./gradlew assembleRelease
  artifacts:
    paths: 
      - ./app/build/outputs/apk/release/app-release.apk


unit-test-job:
  stage: test
  script:
    - ./gradlew testDebugUnitTest
  artifacts:
    reports:
      junit:
        - ./app/build/test-results/testDebugUnitTest/*.xml 
