image:
  name: "docker.io/abb128/android-build:latest"

stages:          # List of stages for jobs, and their order of execution
  - test
  - build

build-job:
  stage: build
  script:
    - echo $KEYSTORE_FILE | base64 --decode > key.jks
    - echo storePassword=$KEYSTORE_PASSWORD > keystore.properties
    - echo keyPassword=$KEY_PASSWORD >> keystore.properties
    - echo keyAlias=$KEYSTORE_ALIAS >> keystore.properties
    - echo storeFile=key.jks >> keystore.properties
    - ./gradlew assembleRelease
  artifacts:
    paths: 
      - ./app/build/outputs/apk/release/app-release.apk


unit-test-job:
  stage: test
  script:
    - ./gradlew testDebugUnitTest
  artifacts:
    reports:
      junit:
        - ./app/build/test-results/testDebugUnitTest/*.xml 
