default:
  image: "docker.io/abb128/android-build:latest@sha256:8df16e2badb5e42d2f5e3862683c7ff0ebdcc348affe059385e42eebef79302f"

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - lint

build-job:
  stage: build
  script:
    - echo $KEYSTORE_FILE | base64 --decode > key.jks
    - echo storePassword=$KEYSTORE_PASSWORD > keystore.properties
    - echo keyPassword=$KEY_PASSWORD >> keystore.properties
    - echo keyAlias=$KEYSTORE_ALIAS >> keystore.properties
    - echo storeFile=key.jks >> keystore.properties
    - gradle assembleRelease -s
    - mv app/build/outputs/apk/release/app-release.apk ./app-release-$CI_COMMIT_SHORT_SHA.apk
    - curl -X POST https://zulip.futo.org/api/v1/messages -u $ZULIP_WEBHOOK --data-urlencode type=stream --data-urlencode 'to="Android Keyboard"' --data-urlencode topic=builds --data-urlencode "content=\"New APK build - https://gitlab.futo.org/alex/voiceinput/-/jobs/$CI_JOB_ID/artifacts/raw/app-release-$CI_COMMIT_SHORT_SHA.apk\""
  artifacts:
    name: "app-release-$CI_COMMIT_SHORT_SHA"
    paths: 
      - ./*.apk


unit-test-job:
  stage: test
  script:
    - gradle testDebugUnitTest -s
  artifacts:
    reports:
      junit:
        - ./app/build/test-results/testDebugUnitTest/*.xml 

lint-job:
  stage: lint
  script:
    - gradle lint -s
  artifacts:
    reports:
      codequality:
        - ./app/build/reports/lint-results-*.xml