name: Documentation Issue
description: Report an issue or suggest a change in the documentation.
labels: ["Documentation"]
title: "Documentation: "
type: task
projects: ["futo-org/23"]
body:
  - type: markdown
    attributes:
      value: |
        # Thank you for opening a documentation change request.

        The [voice-input](https://github.com/futo-org/voice-input) issue tracker is reserved for issues relating to the FUTO Voice Input Android Application. Use the `Documentation` issue type to report problems with the documentation in our code repositories, inside the application, or on [https://keyboard.futo.org](https://keyboard.futo.org)

        Technical writers monitor this issue type, so report Grayjay bugs or feature requests with the `Bug report` or `Feature Request` issue types instead to get engineering attention.

        For general usage questions, please see the [FUTO Keyboard Zulip Channel](https://chat.futo.org/#narrow/stream/53-Keyboard) or the [FUTO Keyboard Discord](https://keyboard.futo.org/discord)

  - type: textarea
    id: keyboard-affected-pages
    attributes:
      label: Affected Pages
      description: |
          Link to or describe the pages relevant to your documentation change request.
      placeholder:
      value:
    validations:
      required: false

  - type: textarea
    id: keyboard-problem
    attributes:
      label: What is the docs issue?
      description: What problems or suggestions do you have about the documentation?
      placeholder:
      value:
    validations:
      required: true

  - type: textarea
    id: keyboard-proposal
    attributes:
      label: Proposal
      description: What documentation changes would fix this issue and where would you expect to find them? Are one or more page headings unclear? Do one or more pages need additional context, examples, or warnings? Do we need a new page or section dedicated to a specific topic?  Your ideas help us understand what you and other users need from our documentation and how we can improve the content.
      placeholder:
      value:
    validations:
      required: false

  - type: textarea
    id: keyboard-references
    attributes:
      label: References
      description: |
        Are there any other open or closed GitLab/GitHub issues related to the problem or solution you described? If so, list them below. For example:
        ```
          - #10
        ```
      placeholder:
      value:
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        **Note:** If the submit button is disabled and you have filled out all required fields, please check that you did not forget a **Title** for the issue.
